groups:
  baseline:
    services:
      - cloudtrail/data
      - firehose
      # examples:
      # - iam/role
      # - vpc
      # - vpc/endlint

  security:
    services:
      - cloudtrail/management
      - guardduty
