groups:
  baseline:
    services:
      - cloudtrail/data
      - firehose
      # examples:
      # - iam/role
      # - vpc/endpoint

  security:
    services:
      - cloudtrail/management
      - guardduty
